# Generated by Django 5.0.1 on 2024-01-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('address1', models.CharField(max_length=80)),
                ('address2', models.CharField(max_length=80)),
                ('count_of_available_places', models.IntegerField()),
                ('total_available_places', models.IntegerField()),
            ],
            options={
                'db_table': 'hosts',
            },
        ),
    ]
